version: '3.8'

services:
  app:
    image: voice-gpt:latest
    container_name: voice-gpt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
